Develop
skywalker0823/taipei-day-trip-website pull request #1
Opened 2022-02-28 04:01 UTC by skywalker0823

楊子軒(pikxl_)

2022-02-28 15:18 UTC, cwpeng commented
I need your online testing URLs.

2022-03-01 04:44 UTC, skywalker0823 commented
http://52.33.215.189:3000/api/attractions?page=1
http://52.33.215.189:3000/api/attractions?page=0&keyword=藝術
http://52.33.215.189:3000/api/attraction/100
請老師檢查謝謝

2022-03-01 06:33 UTC, cwpeng requested changes
景點圖片的部份，顯然不太對勁，請修正後再留言給我重新 Review ~

2022-03-01 06:36 UTC, cwpeng commented
以下這個網址是你的最後一頁資料，其中的 "nextPage" 就必須是 null 代表下一頁已經沒有資料了。
http://52.33.215.189:3000/api/attractions?page=5

2022-03-01 07:48 UTC, skywalker0823 commented
老師您好 以上提及部分都修好了 請老師檢查

2022-03-01 10:53 UTC, cwpeng commented
以下缺少 nextPage 欄位，另外 images 欄位是一個陣列，你這邊輸出的其實是一個字串。
http://52.33.215.189:3000/api/attractions?page=1

2022-03-01 13:52 UTC, skywalker0823 commented
老師您好 以上測試過應該是沒有問題了 再請老師檢查
http://52.33.215.189:3000/api/attractions?page=1
http://52.33.215.189:3000/api/attractions?page=0&keyword=藝術
http://52.33.215.189:3000/api/attraction/100
pikxl_ 楊子軒

2022-03-01 13:59 UTC, cwpeng commented
格式還是不對，整個 Response Body 應該只有一個 "nextPage"，景點資料全都包含在一個 "data" 的底下，請仔細確認處理。

2022-03-01 15:16 UTC, skywalker0823 commented
I hope this time shall pass.
Fixed everything.
The data looks fine now.

2022-03-01 15:22 UTC, cwpeng approved these changes
OK. Good Job.

2022-03-01 15:38 UTC, merged